name: Joseph Thomas
favicon: null
layout_spectrum: 0.0907
typography_spectrum: 0.3831
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#fefdfe'
    - '#393836'
    - '#8d8b7e'
    - '#cad5de'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
