name: Joseph Thomas
favicon: null
layout_spectrum: 0.09236663044430315
typography_spectrum: 0.43995849951170385
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.4440880208276212
  lightness: 0.8210214045830071
  saturation: 0.011882330756634474
  rhythmicContrast: 0.2661099056713283
purpose: []
